### ISSUE TITLE
how can i try it on huggingface spaces? 

### ISSUE THREAD

**Issue by Liusuthu** [AcherStyx/Affective-Computing-Demo#1]
hello, i'm  very interested in this project, but i failed to run by myself because of the env problems, i wander is it possiple for me to try it on hugging face, as demonstrated in the README.md file?

**Comment by Yaojie-Shen** [comment]
> hello, i'm very interested in this project, but i failed to run by myself because of the env problems, i wander is it possiple for me to try it on hugging face, as demonstrated in the README.md file?

Hi, @Liusuthu

Thank you for your interest in our project. Sorry, but we are not familiar with Hugging Face Space. Could you please provide more details about the errors you’re facing?

**Comment by Liusuthu** [comment]
thanks for your immediate reply! When using gradio and hugging face, I'll always face some connection problems because i'm in China :(, so that i can't run this project well...but it's okay now, thanks again!
