### ISSUE TITLE
Can not download the pretrained model

### ISSUE THREAD

**Issue by LPY1219** [AcherStyx/Affective-Computing-Demo#2]
Hi, I am trying to reimplement your demo. However, I can not find the pretrained model. Could you please provide me the link?

**Comment by Varun-GP** [comment]
Please let us know where we can find the pre-trained models.

**Comment by Yaojie-Shen** [comment]
Please check the README carefully. It is already published on the [release page](https://github.com/acherstyx/Affective-Computing-Demo/releases/tag/release).
